### ISSUE TITLE
Highlight "watched" transcripts on MA plot

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#10]
(Note: The things we used to call "genes" I am now calling "transcripts", so that the language in the paper, on the website, and in our conversation can all match).

I just selected a swath of transcripts from the MA plot, and when I hover over them in the table, each one gets highlighted by a dot and circle on the plot. I'm wondering if it's feasible to have the dot always stay (so if 19 transcripts are "watched", 19 red dots are placed on the MA plot, and maybe the larger circle gets added when you hover over specific entries on the table.

This would be particularly useful when changing the MA plot from one comparison to another. If I'm selecting a bunch of transcripts from one corner of an MA plot, then I draw up a new MA plot, my first question is how those transcripts are distributed across the new plot. It would be great to get this overview in the first glance.

**Comment by ptgolden** [comment]
This was in forever but got taken out at some point on accident. Fixed in d26cf4bc5d7db4ec74a7c2a478b4ae0ef70a809e

**Comment by tintori** [comment]
Yea, ok, I thought I remembered it. Cool, thanks!
