### ISSUE TITLE
Landing on WebFaction error page

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#11]
I know you already know this one— just formally filing it.

I'm still having issues loading the page in Chrome, and Bob was having problems with Firefox.

**Comment by ptgolden** [comment]
It's so weird. I'll investigate today. I've never had a problem with any other site I put up there.

**Comment by ptgolden** [comment]
Instead of crawling down that hole, I emailed Hínár to fix the issue about serving from http://dredge.bio.unc.edu/ instead of my domain

**Comment by ptgolden** [comment]
dredge on bio is working now-- I should have an updated client pushed out today or tomorrow. I'll close this when that's the case
