### ISSUE TITLE
Running a "test" sometimes loads a tiny subset of data points

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#15]
While I was setting up a project, the first three time I hit "test", only a few datapoints would appear in the MA plot. They all had P values of 0 or like .001, which made me think there was some non-random filtering happening somehow. 
The final time I tried, all the points appeared for some reason. The only thing I changed between each iteration of tests was the min/max values, but the values that finally worked were the first ones I tried, so I don't think those values made any difference.

**Comment by ptgolden** [comment]
Yeah I ran into that a few times when the logCPM/logFC values were too high. I'll look into it

**Comment by ptgolden** [comment]
Fixed in 4b37916b2798f040e4530c3cff0b1a0f7f01161b
