### ISSUE TITLE
Is "transcript grid" going to be the grid of treatments?

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#17]
I'm not sure what "transcript grid" is exactly, but I'm guessing it might be the layout file for the grid of treatments. True? Still happening, right?

**Comment by tintori** [comment]
We'll need to put some option in for people who aren't using SVGs. Seems like the grid of boxes is already working in the mouse dataset—could we implement that in the configuration page and other project sites as well?

**Comment by ptgolden** [comment]
Finished in 1e332cbfc3abd943b501236cd7a0bed0fcaa2bd6

You can edit the documentation for the field here if you would like: https://github.com/ptgolden/dredge/blob/master/documentation/fields.md
