### ISSUE TITLE
Wormbase (or other-base) link

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#18]
The whole thing looks amazing and it is so exciting to see ones data in this format, ready to be played with. I started clicking around and immediately found some transcripts that I piqued my curiosity. I instinctively looked for a wormbase link and didn't see one. The ___-base search URL should be added to the configuration page, right?

**Comment by ptgolden** [comment]
(re)implemented in 23febc29786be05c3e72b355a50e930ffba317f0
