### ISSUE TITLE
Edits to the "Instructions" text

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#19]
I imagine I'll just do a comb through to edit the text at the end, so these things are not urgent. But for now, we can use this thread to keep track of stuff we notice that should be changed eventually.

- First sentence in directions: "You will need to serve this page via a local Web server on your own machine." For the final version, I imagine this will not be exclusively true, correct? 
- The documentation should have a line that says, in so many words: this uses edgeR (with the following settings, bla bla). if the user has their own statistical method they prefer, they can supply a directory of pairwise comparison files themselves, as long as the first column is transcript id's, the second column is log fold change, the third is log average abundance, and the fourth is p-value
- The text tells them to download the R scripts, but the scripts are already in the zipped package. We can just describe how they should run the commands.
- Tweaks to instructions on how they should run the commands:
	- Suggested command for making JSON file:
		- "Rscript JSON_treatments.R -i expression_matrix.tsv" should be -> "Rscript JSON_treatments.R -i experimental_design_file.tsv"
		- "You can change the output of the JSON file using the '-i' flag in the script" -> should be '-o' flag
	- Suggested command for pairwise script:
		- "Rscript pairwise_comparisons.R -e expression_matrix.tsv -d experimental_design_file.tsv"
		- You can change the directory created for pairwise comparison files with the "-o" flag, and the min/max file with the "-m" flag.
- We describe a file called "projects.json" inside the base dredge folder: dredge-4.2.1/my_project/projects.json. Shouldn't the base folder be dredge-4.2.1/projects.json ?

**Comment by tintori** [comment]
- Clarify that the treatment.json file will download to the user's default download location, and that the user must move it into the dredge directory

**Comment by tintori** [comment]
- The text fields where the user inputs the file path for each component should label clearly which components are required and which are optional.

**Comment by ptgolden** [comment]
Here's a question re: local/remote server-- are you developing your new projects on your own machine? Or on your server?

**Comment by tintori** [comment]
On my own machine. I'm not clever enough to know how to do it on my server (I just upload stuff to that website using filezilla, not any kind of ftp connection or anything, though I wish I did it through the command line..)

**Comment by tintori** [comment]
I'm not sure that typing out suggestions is the easiest way to do this editing step... here's what I have so far. I only just began the right half of the page, and I'm noticing myself skipping some stuff because it seems like too much to type up. If you much prefer this method for some reason, I can continue going through the text this way, but it's very inefficient.

### Configure file directory
The directory where you will save the configuration file you generate from this page, relative to where you will place the index.html file when you upload your DrEdGE project. All of the following settings involving URLs will be resolved relative to this directory.
**[erase this ->]** If you change this URL,**[<-]** it can be relative or absolute, But note that if data will be served from a different host than the DrEdGE page, you will need to set appropriate CORS headers on that host.
### Treatment information URL
Generating using R scripts as described in the instructions. **[this sentence is weird]**
### Pairwise comparison URL template
For example: If my dataset contained the pairwise comparison for treatments T1 and T2 in the directory pairwise_tests/T1-T2.csv **[should just be directory, without the T1-T2.csv part]** the value in this field would be pairwise_tests/%A-%B.csv
DrEdGE expects a pre-generated file for each pairwise comparison of treatments **[cut the rest of this sentence]**containing statistics about the comparison for each different transcript. Instructions about how to generate this file using edgeR can be found to the right. You may use your own statistical package, but DrEdGE will expect that each comparison file will be a tab-separated value with **[add: "one row for each transcript, and following four columns:"] [then cut from here to colon]**the first four columns being: transcript name, log₂ Fold Change, log₂ Reads per Million **[add:(or similarly normalized abundance values)]**, and p-value. The first row will be discarded asd **[remove d]** a header. The **[transcript names] [cut ->]** name of the transcript **[<-]** should match those found in the gene expression matrix.
### Transcript aliases URL
The URL that contains **[cut->]** information about **[<-]** alternate names for transcripts in the dataset. This should be a CSV file whose first column contains the **["most legible transcript name", then cut ->]** canonical label for a transcript **[<-]**, and whose other columns contain alternate names **["or codes for the transcript"]**. One of these columns must contain a value found in the treatment.id column in the project design file described in the instructions.
### Transcript hyperlink template
**[if you want a real life example, this one is general and anyone could just copy and paste into the window: http://useast.ensembl.org/Multi/Search/Results?q=%name;site=ensembl_all]**
**[Would it make sense to replace "URL" with path? Might be more intuitive if people are setting this up on their machines.]**
**[All the future future tense is a little weird, and I think could just be present tense]**
### Diagram URL
The URL of the SVG diagram for this project. This SVG will be a diagram that will allow users to select **[cut]** different **[<-]** treatments to compare and show a**[n illustrated]** **[cut quotes]** "heat map" of transcript abundances among **[cut ->]** different **[<-]** treatments. To **["link SVG objects to treatments", then cut ->]** identify treatments in your SVG **[<-]**, **[cut ->]** you should **[<-]** set the id attribute of the SVG shape (e.g. path, rect, circle) **["to the corresponding treatment id", then cut ->]** that corresponds to a given treatment **[<-]**. **[cut ->]** The value of the id attribute must be the same as the unique treatment identifier given in the treatment information file. **[<-]**
### Setting up dredge
Once you have your local application up and running, visit this page there **[this is confusing and suggests going back to dredge.bio.edu. Perhaps should say "visit the index.html page from that directory" instead]**
**[you switch from second person singular to first person plural halfway down]**
Because we will put all of our project files in this directory, The Configuration **[the last two words are not supposed to be capitalized, right?]** file directory field to the left has been already filled out with the value ./data/

**Comment by tintori** [comment]
Typing into the hyperlink label and hyperlink URL text boxes doesn't do anything—no text appears in the boxes.

**Comment by tintori** [comment]
Whoops, that's not a text thing per se, that's a bug. Gonna start a new thread for that, sorry this is getting a little sloppy.

**Comment by tintori** [comment]
More about the instructions:
It says after all the index.html file has been edited, to refresh this page (i.e. http://localhost:8000/?page=configure), but that doesn't do anything. The instructions should say to go to http://localhost:800 instead (or whatever), right?

**Comment by ptgolden** [comment]
> I'm not sure that typing out suggestions is the easiest way to do this editing step... here's what I have so far. I only just began the right half of the page, and I'm noticing myself skipping some stuff because it seems like too much to type up. If you much prefer this method for some reason, I can continue going through the text this way, but it's very inefficient.

Imagine typing up all this garbage for the first time!

I'll convert things to a format where you can edit it. Are you familiar with editing files and suggesting changes with git at all?

**Comment by ptgolden** [comment]
OK, I made it into a markdown file so that it will be easier to change. I can do the individual fields (and the "About DrEdGE" page) tomorrow.

If you want, you can edit that page (the little pencil icon", and select the "Create a new branch for this commit and start a pull request. Learn more about pull requests." option at the bottom

**Comment by ptgolden** [comment]
Oh, whoops, it's here: https://github.com/ptgolden/dredge/blob/master/documentation/instructions.md

**Comment by ptgolden** [comment]
And here's the instructions for each field in the form:
https://github.com/ptgolden/dredge/blob/master/documentation/fields.md

Can you edit these with a pull request?

**Comment by ptgolden** [comment]
(You'll see the separation between the fields if you edit the file)

**Comment by tintori** [comment]
How do I edit with a pull request? Is that what I did before (by hitting the "Create a new branch for this commit and start a pull request." toggle at the end?), or something else?

**Comment by ptgolden** [comment]
https://help.github.com/en/articles/editing-files-in-your-repository

**Comment by tintori** [comment]
Ok. I'm pretty sure I did all of that except adding a description. Let me know if I bunged anything up.

**Comment by ptgolden** [comment]
Hmmm, did you press the "Propose file change" button ? If it worked, you would see it here: https://github.com/ptgolden/dredge/pulls

**Comment by tintori** [comment]
Oh lord, I'm not sure where that button is... I can find the branch I made or patch or whatever: https://github.com/ptgolden/dredge/blob/9f10df9b995328988680a5a2fc11e9f025e40c11/documentation/fields.md
But I'm not sure where the propose file change option was in the process...
Also, in searching around just now I accidentally made a fork (?), I should stop clicking stuff.

**Comment by tintori** [comment]
Feel free to sever my fork, if that's something you can do and care to.

**Comment by tintori** [comment]
I'm going to delete the tintori/dredge repository I just accidentally made... I feel quite certain that it's fine, but github's warnings are making me want to check with you that it won't affect anything on your end first. Fine, right?

**Comment by tintori** [comment]
I did this the first time (hit the propose file change button), and just tried it again:

![Screen Shot 2019-04-01 at 5 47 43 PM](https://user-images.githubusercontent.com/7449762/55361852-5e9a8500-54a6-11e9-838d-a78408b0c6ca.png)

Was there anything weird there? I still don't see any pull requests.
