### ISSUE TITLE
"project.json" not saving to root directory

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#22]
When I saved my project, it saved to the desktop (my default download destination), not my root directory as described in the text.

**Comment by ptgolden** [comment]
We can't do anything about where a file saves, since, as you point out, it's controlled by the browser. I can clarify that you have to browse to that folder I guess?

**Comment by tintori** [comment]
Ok, great, I'll add that to the thread of edits to eventually make to the text.
