### ISSUE TITLE
projects.json could be a file that comes in the zipped package?

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#23]
Could the projects.json come with the package, and we just ask the first user to edit it? That way it can already have our three sample datasets in there, which the first user can remove or replace as they wish. (maybe it would even have a commented out line saying as much).

This issue may end up being moot if we scrap the multiple-projects-on-one-website feature, which we can disuss in a different issue thread...

**Comment by ptgolden** [comment]
If we do what I suggested in https://github.com/ptgolden/dredge/issues/25#issuecomment-471571145, yes, this would be moot. The URL to the configuration file could be set in `index.html` instead, with a template on what should appear there

**Comment by ptgolden** [comment]
This is now the case. The index.html file contains a line that says:

```
    <script type="text/javascript">
      // To configure DrEdGE to load your project, uncomment the line below this
      // paragraph, changing the string the location of the JSON configuration
      // file you generated with the project configuration form.
      //
      // window.DREDGE_PROJECT_CONFIG_URL = 'path/to/project.json'
    </script>
```
