### ISSUE TITLE
"Help" vs "About DrEdGE" vs "About the dataset"

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#24]
I think the item currently named "help" in the menu should be named "about dredge", and there should be a separate place for the first user to upload a file that will be called "About the dataset"

**Comment by ptgolden** [comment]
:+1:

I'll add this. The "About the dataset" feature will be another field in the form. I haven't gotten around to implementing it yet.

**Comment by ptgolden** [comment]
Implemented in c39aef84e53f46aad12ab1ebc6da45698e597810
