### ISSUE TITLE
projects.json feature might not be necessary

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#28]
Now that I'm seeing it all in place, I'm not sure there is added value from having the dropdown menu where you can switch between projects. I think it will be extremely uncommon for a lab to publish more than one project at a time. It may be just as useful (and simpler to create) if there was just a separate URL for each project. 

We can chat more about this though.

**Comment by ptgolden** [comment]
With the single-project-per-site architecture, where should our individual projects live now?

Could be:

http://dredge.bio.unc.edu/c-elegans-gastrulation
http://dredge.bio.unc.edu/human-neuronal-tissue
http://dredge.bio.unc.edu/mouse

?

Or should the URLs have the name of the labs (or something like that)?


At http://dredge.bio.unc.edu/ we can have a small page with documentation about the project

**Comment by tintori** [comment]
Yea, exactly, I think they would each get separate, descriptive URLs. 

I would make them:
http://dredge.bio.unc.edu/c-elegans-timecourse
http://dredge.bio.unc.edu/human-neuronal-tissue
http://dredge.bio.unc.edu/mouse-embryonic-tissue

**Comment by ptgolden** [comment]
Perfect. I think I will have time to finish this and put those up tomorrow.

**Comment by ptgolden** [comment]
Implemented in #31

**Comment by ptgolden** [comment]
OK, those links should work now :tada: :tada: :tada: :tada:

Not everything is 100% functional (watched transcripts aren't getting persisted correctly, I need to tweak some stuff with page titles), but... yay!

**Comment by tintori** [comment]
Woohoo!
