### ISSUE TITLE
Resizing to the window is still a little funky

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#29]
I ran into a bug.. this how I accidentally got there:

My window was zoomed way in (~200%) from some screengrabs I was doing earlier, and I loaded the dredge page:
![Screen Shot 2019-03-13 at 5 21 21 PM](https://user-images.githubusercontent.com/7449762/54315525-bbe09c00-45b4-11e9-98f3-a4d5dcccfd7a.png)

Then I zoomed back down to 100% (I know this part is supposed to look weird):
![Screen Shot 2019-03-13 at 5 21 43 PM](https://user-images.githubusercontent.com/7449762/54315551-cc911200-45b4-11e9-843d-9d691fda16b4.png)

Then I pressed the resize button:
![Screen Shot 2019-03-13 at 5 21 52 PM](https://user-images.githubusercontent.com/7449762/54315560-d3b82000-45b4-11e9-88bc-f14917ed1a6d.png)

**Comment by ptgolden** [comment]
I did the easiest thing possible, which is add a minimum height/width (in b87c94922461fdb030882a74711a62ef08916b6c). I had done that before but the minimum width slipped out somewhere along the way. There could be more elegant solutions, but they would take a lot more time. Let me know if this works enough. (It's v6.5.0, uploading now). This fixes #45 as well.
