### ISSUE TITLE
Dragging a box to select transcripts is overselecting

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#30]
I tried to grab just the top row of boxes (you can see my gray selection area), and it selected way more (everything in purple).
![Screen Shot 2019-03-13 at 5 26 30 PM](https://user-images.githubusercontent.com/7449762/54315762-707abd80-45b5-11e9-8be8-feab13d4c09d.png)

**Comment by tintori** [comment]
Hmm, it also seems to be not selecting everything within the gray box. There should be seven selected here, and only four are selected, one of which is outside of the 7 I was aiming for.

![Screen Shot 2019-03-13 at 5 30 49 PM](https://user-images.githubusercontent.com/7449762/54315951-e848e800-45b5-11e9-891f-a06d7a792703.png)

**Comment by tintori** [comment]
Ok, I guess maybe it's selected like a shadow box that is the same size but offset to the right and down. Again, compare gray box to purple transcripts.

![Screen Shot 2019-03-13 at 5 34 08 PM](https://user-images.githubusercontent.com/7449762/54316110-4fff3300-45b6-11e9-8e82-cda0069ee89c.png)

**Comment by tintori** [comment]
I haven't seen this problem for a while.. might have been something funky going on with my browser. I'm gonna close it unless you think there's something worth looking into here.
?

**Comment by ptgolden** [comment]
This was fixed in e236b0b8043e53e96d58e02f89e3d475d5acb356. The problem was that the "brush" area (the place where you can click and drag to select) was not reset after resizing the screen. So, if the screen was slightly larger/smaller, it would select the old area instead of the resized one.
