### ISSUE TITLE
Imported transcript list does not show up in the table

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#32]
I've been making a new website with some other data I'm working with (sophiatintori.com/05-dredge/), and I just tried importing a list of transcript names (such as this one).

[HOX.txt](https://github.com/ptgolden/dredge/files/3001547/HOX.txt)

When I upload them, the red dots appear on the MA plot, but the transcripts do not populate the table. Then, when I change the treatments in the MA plot, all the data seems to disappear (though the red dots still move around to their appropriate new places). 

![Screen Shot 2019-03-25 at 12 47 05 AM](https://user-images.githubusercontent.com/7449762/54895757-89c61880-4e97-11e9-97b6-14df659331cf.png)

**Comment by ptgolden** [comment]
What version is this on?

**Comment by ptgolden** [comment]
4.2.2, I see

**Comment by tintori** [comment]
Just tried this again on v6.4.1 and it looks beautiful. Closing, unless there's anything else you wanted to do here?
