### ISSUE TITLE
Move to new homepage

### ISSUE THREAD

**Issue by ptgolden** [ptgolden/dredge#34]
The new homepage will be a list of existing projects, a brief description of DrEdGE, and a link to the zip file. I'll make it this evening.

**Comment by tintori** [comment]
For some reason when I load dredge.bio.unc.edu I get this error page:

![Screen Shot 2019-03-28 at 9 33 37 PM](https://user-images.githubusercontent.com/7449762/55203357-6c4bc400-51a1-11e9-857d-8a92bac8f401.png)

And then if I do a hard refresh it goes to the right page. I tried this a few times and it happens consistently.

**Comment by tintori** [comment]
Oops, the first download link is broken:

![Screen Shot 2019-03-28 at 9 43 39 PM](https://user-images.githubusercontent.com/7449762/55203667-9782e300-51a2-11e9-8ab0-6aab11699846.png)

**Comment by tintori** [comment]
There are a ton of little edits to the text I'd like to make. I was keeping track for a while, but it's a lot, like changes of tense and person and weird aberrant capitalizations throughout... Do you think I could just see the html file for that page and do a proofread/edit of the text myself?

**Comment by ptgolden** [comment]
https://github.com/ptgolden/dredge-deploy/blob/master/index.html

**Comment by tintori** [comment]
For the "Pairwise comparison URL template" text box

- Default should be set to "%A\_vs\_%B" instead of "%A_%B", because the R script generates the former
- For some reason when I type into that box, after each key stroke it sends my cursor to the end of the text box. Not an issue if you're typing the whole string start to finish, but a little weird when you're editing the middle of the text.

**Comment by ptgolden** [comment]
Oh, if you're talking about the text for the instructions, can you put it in that issue? (#19)

That's not generated from an HTML file, it's here:

https://github.com/ptgolden/dredge/blob/master/src/components/NewProject.js

It would probably be easier if you just made suggestions

**Comment by tintori** [comment]
Oh, duh, I have the html file.

If I want to edit a bunch of the text, should I do it in dredge-6.1.0.js and send that to you, or should I just copy and paste the text, make the edits, and send you just the copy?

**Comment by tintori** [comment]
Oh, sorry, your comment hadn't loaded yet when I typed that last one in. And shit, yea, you're right I'm talking about instructions. Ok, I'll move over there.

**Comment by tintori** [comment]
Ok, here's one that's **actually** for the homepage:
The "Timecourse of _C. elegans_ gastrulation" link should be called: "Whole embryo time course of _C. elegans_ development", or just "Time course of _C. elegans_ development" if the length is awkward.

**Comment by ptgolden** [comment]
Done in https://github.com/ptgolden/dredge-deploy/commit/ff4f2528ed8ae56181a6ebce47f34c5e39ec7c18
