### ISSUE TITLE
Issues when trying to configure a new project

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#35]
For the "Configure the file directory" text box, when I test the settings and then return to editing, this always switches back to the default (./data/), rather than whatever I put in. None of the other boxes do this.

**Comment by tintori** [comment]
The two text boxes for the hyperlink label and URL cannot be typed into.

**Comment by tintori** [comment]
(What I accidentally put in the "homepage" issue earlier this evening:)

For the "Pairwise comparison URL template" text box
- Default should be set to "%A_vs_%B" instead of "%A_%B", because the R script generates the former
- For some reason when I type into that box, after each key stroke it sends my cursor to the end of the text box. Not an issue if you're typing the whole string start to finish, but a little weird when you're editing the middle of the text.

**Comment by tintori** [comment]
All the files and paths I enter seem to be loading fine, but the MA plot is not becoming populated with dots, and the console is logging errors like this: 

> dredge-6.1.0.min.js:478 Warning: 16348 transcripts in sample but only 0 put in bins

**Comment by tintori** [comment]
(Ok, this last one was resolved by setting the min/max values lower. It was zoomed out to the default settings, and nothing was showing up)

**Comment by tintori** [comment]
To add to the last note: I run into the same issue if the min and max are zoomed in too tight. No dots show up when I divide the normal mins and maxes by 10.

**Comment by ptgolden** [comment]
Your last three comments were all related to #15 . They should be fixed by 4b37916b2798f040e4530c3cff0b1a0f7f01161b

**Comment by ptgolden** [comment]
> For the "Configure the file directory" text box, when I test the settings and then return to editing, this always switches back to the default (./data/), rather than whatever I put in.

Fixed in 451db32cea4c0d4264cba2c482a3d32d13e93ee4

**Comment by ptgolden** [comment]
> Default should be set to "%A_vs_%B" instead of "%A_%B", because the R script generates the former

cbf89ab2fbf7dc1c85659284fd55c2e64ed6973d

**Comment by ptgolden** [comment]
> For some reason when I type into that box, after each key stroke it sends my cursor to the end of the text box. Not an issue if you're typing the whole string start to finish, but a little weird when you're editing the middle of the text.

I know what's causing this, but I haven't fixed it yet

**Comment by tintori** [comment]
When constructing a new dredge page with my friend Amy's data, the program ran well when I tested it, then wouldn't load data onto the MA plot when I was running it locally on my computer, but then when I uploaded it to the web (thinking I'd share it with you, to show you the problem), it worked online. Do you know why it would not work locally but work fine online?

This is the uploaded version: http://sophiatintori.com/05-dredge/index.html

**Comment by tintori** [comment]
(These are screengrabs of the problem I was running into when I tried to look at a local version of the page. This is what I would see if I already had developer tools open when loading the page...) 

![Screen Shot 2019-04-22 at 11 46 02 AM](https://user-images.githubusercontent.com/7449762/56512396-375f3280-64fd-11e9-9dc1-feeebbc9dcf0.png)

(... and this is what I would see once I closed developer tools, or if I loaded the page without developer tools open.)

![Screen Shot 2019-04-22 at 11 46 24 AM](https://user-images.githubusercontent.com/7449762/56512400-3a5a2300-64fd-11e9-89b2-3feb90ac4c12.png)

**Comment by ptgolden** [comment]
No, I can't tell from that.

I'm going to close this issue because all the original things are finished, as far as I can tell. Add new issues if there's anything else.
