### ISSUE TITLE
A couple of ideas for the menu

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#36]
- As far as I can tell there is no link on the 3 project websites that bring the viewer back to dredge.bio.unc.edu. We should probably have something like that in the menu, no?
- I still think "About" should be "About the dataset". I know you put it in a section of the menu that is dataset-specific, but I'm not sure it's obvious enough to block the instinct of thinking "About" means about the website or the larger project.

**Comment by ptgolden** [comment]
> As far as I can tell there is no link on the 3 project websites that bring the viewer back to dredge.bio.unc.edu. We should probably have something like that in the menu, no?

Do you think this should be in the menu? Or on the "About DrEdGE" page?

> I still think "About" should be "About the dataset". I know you put it in a section of the menu that is dataset-specific, but I'm not sure it's obvious enough to block the instinct of thinking "About" means about the website or the larger project.

You're right, done in e2d3d9f121ad5c29097886be3177e5bbc80ec1b9

**Comment by tintori** [comment]
Bob, too, was looking for a "DrEdGE home" item in the menu.

**Comment by tintori** [comment]
Oh, I see a "Home" item in the menu on the "About" page. But that link is broken.

**Comment by tintori** [comment]
> > As far as I can tell there is no link on the 3 project websites that bring the viewer back to dredge.bio.unc.edu. We should probably have something like that in the menu, no?
> 
> Do you think this should be in the menu? Or on the "About DrEdGE" page?

I would put it in the menu.

**Comment by ptgolden** [comment]
Done in 855465ccbf493d1a3bee7fa1ed64dd20bad684c9
