### ISSUE TITLE
"Please cite as" needs to be replaced

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#38]
The new citation should be:

> Tintori SC, Golden P, Goldstein RP. Differential Expression Gene Explorer (DrEdGE): A tool for generating interactive online data visualizations for exploration of quantitative gene expression datasets [in preparation]

**Comment by ptgolden** [comment]
Done

**Comment by ptgolden** [comment]
(in 99b6b3df5b4dd937a0096a938e98c0282bcfde72)
