### ISSUE TITLE
Making names readable

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#4]
- the name of the MA plot is treatment1code-treatment2code (ie ENCSR636CWO) instead of the verbose name. 
- the name of genes in the table and the heatmap is code name from the RPKM table (ie ENSMUSG00000029306) instead of more verbose name from first column of the alternate gene name table.

**Comment by ptgolden** [comment]
Sorry, can you tell me what each should be? I think I understand the first point-- the MA plot should be the label of the treatment given in `treatments.json` (right?), but what do you mean in the second?

**Comment by ptgolden** [comment]
I'm fixing this right now, but FYI, I think there's a problem in human_alt_gene_names.txt. The rows have both commas and tabs to separate fields. I changed everything to be commas, but there might be something you want to change in the pipeline.

**Comment by ptgolden** [comment]
Fixed in eaff52ea40ba32c39a73a19411592ff744bcb169 and 5ac4c142690d87e50bcb0e063b3ced81f7c0a571
