### ISSUE TITLE
Export function only exports gene names

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#41]
It would be great to export the whole data table with all the stats.

**Comment by ptgolden** [comment]
To do this, I would need to add headers to the export file. Should the "import gene names" function work the same way (i.e. expect headers to be present)?

**Comment by tintori** [comment]
Hm, good question. 
Would it be feasible to have the import function *not* expect headers, but then if the first entry in the first line doesn't match anything in the RPKM table rownames, the first row is disregarded?

**Comment by ptgolden** [comment]
Yeah, that's the only thing I would thinking would work to have the exported files be importable. I guess I'll just check if the first line matches the exact characters `name`. That would be a truly strange gene name, and it would be a one in a trillion coincidence to have it be first in a list.

**Comment by ptgolden** [comment]
Exporting done in ca37caf4926270d0c2ebd48f8dc335770343b5ce

**Comment by ptgolden** [comment]
Ah dang, I accidentally took out the screen where it told you how many transcripts were imported and how many weren't. Adding in now as a adapt the import function to work with the new format of the export table

**Comment by ptgolden** [comment]
Done in 0d986b13d9526ca0de3d719bdc9e852cbd26de4b
