### ISSUE TITLE
Heatmap key is out of bounds

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#45]
It's fine when there's only 4 items in the key, but looks funky when there are more.

**Comment by ptgolden** [comment]
I don't understand what you mean

**Comment by tintori** [comment]
Here are some examples from the mouse dataset:

![Screen Shot 2019-04-23 at 1 41 31 AM](https://user-images.githubusercontent.com/7449762/56557422-f3097c00-6568-11e9-87c5-257b4af4812c.png)

![Screen Shot 2019-04-23 at 1 41 19 AM](https://user-images.githubusercontent.com/7449762/56557428-f7359980-6568-11e9-965b-8bb416cfff0e.png)

![Screen Shot 2019-04-23 at 1 41 11 AM](https://user-images.githubusercontent.com/7449762/56557436-fd2b7a80-6568-11e9-883d-b79e1855e475.png)

**Comment by ptgolden** [comment]
Ah. Let me revisit resizing (which I'm doing now) and see if that fixes this.

**Comment by ptgolden** [comment]
Didn't mean to close
