### ISSUE TITLE
MA plot is flipped on the y-axis

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#51]
I used 6.4.1 to create a website using my friend Amy's data, and ran into a couple of little problems. The most urgent one is that the MA plot seems to be upside down again. You can look around for yourself, if you'd like, at http://sophiatintori.com/05-dredge/index.html.

In this screengrab, Head vs Back is selected, and all the highlighted transcripts should be more abundant in the Head according to the MA plot, but they are all more abundant in the back according to the heatmap.

![Screen Shot 2019-04-22 at 12 19 50 PM](https://user-images.githubusercontent.com/7449762/56511022-830fdd00-64f9-11e9-8744-406b118efc98.png)

**Comment by ptgolden** [comment]
Is it upside down on existing data? If not, it's probably your problem generating it.

**Comment by ptgolden** [comment]
You had me flip it once before. Would you like me to do it again?

**Comment by tintori** [comment]
Hmm, good thinking, you're right—it is a difference in the data files. The existing ones are still correct

Ok, the pairwise comparison files for this new dataset were generated using the other popular R package (that people usually use if they're not using edgeR), and it generates fold changes that are flipped from the way edgeR generates them. Let's leave it as you already have it, and maybe (later) add a note to the documentation warning people to double check that, since different programs generate fold changes in opposite ways.

**Comment by ptgolden** [comment]
That's a really strange thing. Does the sign of a fold change mean the opposite thing in that library? What about other ones?

**Comment by tintori** [comment]
Yea it's dumb. "Fold change" doesn't specify if it's a change *up* or a change *down*, from the first sample to the second. edgeR defines it as down and DESeq2 (the other package) defines it as up, apparently. I googled a little bit, and it seems there are two opposite and equally correct ways to calculate fold change.

**Comment by tintori** [comment]
Wait, I'm looking at some examples from the data again and getting a little scrambled. Let me take a second to make sure I have it straight.

**Comment by tintori** [comment]
Ok, confirmed. What I said two comments up is mostly true, except edgeR considers foldChange *up*, and DESeq2 considers fold change *down*. 

The way we have it built right now accommodates edgeR, which is what the R script we're supplying uses, and which ascribes a positive fold change when abundance increases from treatment1 to treatment2, which I think is more intuitive. So let's keep it as is. 

I'll add an edit to the field descriptions later today for DESEq users to watch out for that.

**Comment by ptgolden** [comment]
That's really funny. I'm going to close this issue, then, and wait for a PR for the instruction edits
