### ISSUE TITLE
`TypeError: Cannot read property 'toString' of undefined` when selecting a transcript in the search results

### ISSUE THREAD

**Issue by JonathanSeguin** [ptgolden/dredge#53]
While in human neuronal tissue (http://dredge.bio.unc.edu/human-neuronal-tissue) , I did a transcript search for ALG1 and clicked the first one and fell on ```TypeError: Cannot read property 'toString' of undefined```. This does not seem specific to ALG1, the same error happened to another transcript.

The application is stuck on that error as the localstorage keeps cached the search selection (if I go in chrome console and remove it, the app is OK)

My hunch is that this error happens for transcripts that share a gene symbol name (shown in parenthesis in the search results). Some transcript that seemingly are the only one attached to a particular gene symbol in the dataset seem ok. (then again this is just a hunch... I might be wrong!)

![Screenshot from 2019-05-03 15-13-39](https://user-images.githubusercontent.com/576915/57160210-1ed10100-6db6-11e9-93d9-37524291f34b.png)

**Comment by ptgolden** [comment]
This was an issue with formatting undefined values in the table for a given transcript. It should be fixed now (in version 6.8.1)

**Comment by JonathanSeguin** [comment]
Looks good!
