### ISSUE TITLE
P-value text box seems to be lying

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#6]
If I type in .00001 to the p-value cutoff text box I get the same MA plot as if I type in .00000001 (or anything smaller than .00001). 

If the P-value column only goes down to 5 sig figs, shouldn't .000000001 give me an empty plot?

**Comment by tintori** [comment]
This looks good, but now I'm realizing that once you get down to the <0.001 P-values, they all say 0.000 in the table. Certainly the real P-values round to this, but if there's a way to format them to go into 1e-4 or whatever type format (as it does in the box you type the P-value filter into), that will make the column much more useful.

**Comment by tintori** [comment]
One more P-value problem that was noticed by a graduate student in the Goldstein lab: 

If there is a rectangle of transcripts highlighted on the MA plot, and then the user goes to adjust the P-value filter, the box goes away, as do the transcripts in the table. It would be great to have the box and transcript details remain.

**Comment by ptgolden** [comment]
Setting p value changed in 1f017507ad374320b73e7f6a629c8f6ecc898193

**Comment by ptgolden** [comment]
p-value in table displaying < .001 fixed in 3e57af42efc8bb923ddbdabb65a167748d20a2a5

**Comment by ptgolden** [comment]
I'm having some issues with p-values in the c-elegans-embryo dataset while making a slider that will work with a logarithmic scale. For some treatments in some comparisons, the matrix sets a p-value of 0. Is that correct? Or is it just rounding down? It makes it difficult to create a lower baseline for a logarithmic scale, but I could work around it if that's expected behavior.

For example, there are lots in minute_53_vs_minute_82.txt (B0285.7, C01G6.1, C06G8.1, and so on..)

**Comment by tintori** [comment]
You’re right, these are most likely rounded down, but we should definitely be prepared to expect some zeros in people’s datasets, like these.
 
This is an interesting question though—if the dataset only has 5 significant figures, and the user asks for p-values below .0000001 or something, how to represent that there are zeros in the dataset, but because of rounding they are not necessarily lower than .0000001.

My primary priority is that the solution be whatever is easiest for you. One idea that comes to mind, though, is that the lower limit of the p-value slider could be set according to how many significant figures are in the uploaded data tables. I don’t know how involved that would be, though, so feel free to ignore that idea if it’s too complicated, and do whatever you need to do here, even if it doesn’t resolve that little (0 !< .0000001) contradiction.

**Comment by ptgolden** [comment]
> One idea that comes to mind, though, is that the lower limit of the p-value slider could be set according to how many significant figures are in the uploaded data tables.

Yes, that's what I'm doing with making the slider work on a logarithmic scale. I'll just make the lower bound of the slider the lowest non-zero value there is. (That doesn't mean that zero values will not be included, just that they will not have special status in the slider).

**Comment by tintori** [comment]
Cool, that sounds great.

**Comment by tintori** [comment]
I've made a change to the pairwise_comparison.R script: It now prints out P-values in scientific notation, simplified to two significant digits (ie 0.43 or 9.2e-24), instead of rounding to some arbitrary decimal position, as it was doing before. 

I made all new pairwise comparison files with the new script, tried pushing them through dredge-6.7.0, and it integrates very nicely, no hiccups at all. So it seems like this shouldn't change anything you're working on on your end, but I thought I'd mention that the data look a little different now. There *are* still some zeros in these files anyways, so it would still be good to be prepared to handle P-values of zero.

Because of this change, there are a few sets of updated files in the Dropbox folder to grab and upload eventually: 
- The pairwise_comparison.R script
- All three directories of pairwise_files
- All three project.json files

**Comment by ptgolden** [comment]
I uploaded all the changes you made. Can you look at the new p-value selector and tell me if it's OK? I'm going to make sure everything is lined up a little more, but it's a good crack at it.

**Comment by tintori** [comment]
This looks fantastic! The slider really shows the shape of the data now—so much so that at first glance I'm learning new things about the data (and fundamental differences between the characters of each dataset) that I didn't know earlier. So cool how this has become more than just a setting for the visualization, but has become an intellectually stimulating data viz feature in its own right. It really invites the user to play. Very nice.

I'm noticing a couple of little funny formatting features, one of which is superficial, and the other of which affects the values of the numbers only a little bit. Feel free to follow your own judgement about whether you want to deal with them—they are not show stoppers for me.

1. All negative logFC values are being converted to "e"-based notation, even if they are within the -1 to -10 range. This is not happening for positive logFC values.
2.  Zeros are being added to logATA values. This means it is reporting data that wasn't actually uploaded (i.e. 6.86123 in the original data is uploaded as 6.9 and then reported as 6.90, suggesting a degree of accuracy that wasn't actually provided).

Here are a couple examples from the human dataset, parietal vs tibial nerves.

Original pairwise comparison table

| Name  | P-Value  | logATA  | logFC  |
|---|---|---|---|
| ENSG00000100906 (NFKBIA)  | 2.9e-06  | 6.9  | -7.4  |
| ENSG00000187288 (CIDEC)  | 2.6e-06  | 3.1  | -6.1  |

Dredge table

| Name  | P-Value  | logATA  | logFC  |
|---|---|---|---|
| ENSG00000100906 (NFKBIA)  | 2.9e-06  | 6.90  | -7e+1  |
| ENSG00000187288 (CIDEC)  | 2.6e-06  | 3.10  | -6e+1  |

**Comment by ptgolden** [comment]
Both of those should be fixed now (I think). Can you confirm?

**Comment by tintori** [comment]
Yes, it looks great!

**Comment by ptgolden** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by tintori** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
