### ISSUE TITLE
Default heatmap graphics: boxes in a compact grid

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#9]
It would be great to have a default function for the heatmap. This is what I'm thinking: 

If no svgs or grid.csvs are submitted, all treatments are shown as box icons, and the boxes are arranged in a compact grid with a ~5x2 aspect ratio (or something like that).

**Comment by tintori** [comment]
They could even just be arranged in a single horizontal line, that would be cool too.

**Comment by tintori** [comment]
I can write an R script to include in the package, that accepts a metadata file and returns a grid.csv file for this simple compact box arrangement.

**Comment by ptgolden** [comment]
Finished in 6aa984271b5719cd8ceb7c1dd9b534e0c05f0854
